### PR TITLE
Updated the template so that it could work on any region

### PR DESCRIPTION
**Pull request by femee24**
PS: will only work once the chef recipes are updated as well
https://github.com/TORO-IO/toro_integrate_cloudformation_cookbooks.git

### CODE REVIEW

**Comment by jairenzbatu** [comment]
We'll wait for the cookbook updates @femee24

**Comment by femee24** [comment]
@jairenzbatu done with the PR, kindly review

**Comment by jairenzbatu** [comment]
Looks good to me, btw if the document needs to updated also. let @michaellacastro know.

**Comment by femee24** [comment]
@jairenzbatu noted that.
@michaellacastro will tag you on the issue for the documentation to be reviewed. Thanks

**Review by toro-repo-scans — COMMENTED** [review]
@femee24, Is this working on all regions? If not, maybe we can limit the choices to supported regions only.

**Comment by jairenzbatu** [comment]
btw don't test it yet on all regions @femee24

**Pull request merged**
